dist: trusty

matrix:
    include:
        - os: linux
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty-5.0
              packages:
                - clang-5.0
          env:
            - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

language: node_js
node_js: "8.12.0"

install: travis_wait 120 npm install --clang=1
script: npm test
